using UnityEngine;
using DCC.Core.Tags;
using DCC.Core.Effects;
using DCC.Core.Entities;
using DCC.Items;

namespace DCC.Core.Achievements
{
    /// <summary>
    /// Defines an achievement that can be awarded by the System AI.
    ///
    /// In the DCC books:
    ///   - Achievements are generated by the System AI as crawlers progress
    ///   - Notifications are snarky, petulant, and often backhanded compliments
    ///   - Achievements may reward loot boxes (up to Platinum tier at the System AI's discretion)
    ///   - Floors 1–2 have generic/tutorial achievements
    ///   - Later floors have increasingly unique, crawler-specific achievements
    ///   - Functions: reward playing, warn of danger, notify wrong track, nudge tactics
    ///
    /// Example achievements from the books:
    ///
    ///   "Trailblazing Crazy Cat Lady":
    ///     Trigger: FirstTagCombination
    ///     RequiredTags: [Player, HasPet, Cat]
    ///     Description: "You are the first crawler to enter the dungeon with a cat."
    ///     Reward: Legendary Pet Box
    ///     → First crawler to enter with a cat pet.
    ///
    ///   "Wow, You Actually Hit Something":
    ///     Trigger: FirstKill
    ///     Description: "You've killed your first mob. Congratulations. The bar was low."
    ///     Reward: Iron Adventurer Box
    ///
    ///   "Peak Human":
    ///     Trigger: StatMilestone
    ///     MilestoneStat: Strength, MilestoneValue: 100
    ///     Description: "Your Strength has reached 100. Choose a milestone perk."
    ///     Reward: 3 minutes to choose one of three permanent upgrades
    ///     → In the books, hitting 100 in any stat grants a special achievement.
    ///
    ///   "Social Butterfly":
    ///     Trigger: StatMilestone
    ///     MilestoneStat: Charisma, MilestoneValue: 25
    ///     Description: "Your Charisma is now 25. People like you. Mobs still don't."
    ///     Reward: Bronze Adventurer Box
    ///
    ///   "Floor Survivor":
    ///     Trigger: FloorReached
    ///     RequiredFloor: 3
    ///     Description: "You made it to Floor 3. Time to pick a class. Choose wisely. Or don't."
    ///     Reward: Silver Adventurer Box
    ///
    ///   "Emergent Genius":
    ///     Trigger: FirstTagCombination
    ///     RequiredTags: [Healing, Gas, Smoke]
    ///     Description: "You created a healing smoke cloud. The System is... impressed."
    ///     Reward: Gold Adventurer Box
    ///     IsGlobalFirst: true (only first crawler to do this gets it)
    /// </summary>
    [CreateAssetMenu(menuName = "DCC/Achievement", fileName = "Achievement_New")]
    public class AchievementDefinition : ScriptableObject
    {
        [field: SerializeField] public string DisplayName { get; private set; }
        [field: SerializeField] public Sprite Icon { get; private set; }
        [field: SerializeField, TextArea] public string Description { get; private set; }

        [Header("Trigger")]
        [field: SerializeField] public AchievementTrigger Trigger { get; private set; }

        [Header("Trigger Conditions")]
        [field: SerializeField, Tooltip("For TagCombination/FirstTagCombination: entity must have ALL of these tags.")]
        public TagDefinition[] RequiredTags { get; private set; }

        [field: SerializeField, Tooltip("For StatMilestone: which stat must reach the milestone value.")]
        public CrawlerStat MilestoneStat { get; private set; }

        [field: SerializeField, Tooltip("For StatMilestone: the stat value that triggers this achievement.")]
        public int MilestoneValue { get; private set; } = 100;

        [field: SerializeField, Tooltip("For FloorReached: the floor number that triggers this.")]
        public int RequiredFloor { get; private set; }

        [field: SerializeField, Tooltip("For SkillMaxed: the skill that must reach max level.")]
        public Abilities.SkillDefinition RequiredSkill { get; private set; }

        [Header("Uniqueness")]
        [field: SerializeField, Tooltip("If true, only the FIRST crawler to trigger this gets the achievement (global first).")]
        public bool IsGlobalFirst { get; private set; }

        [field: SerializeField, Tooltip("If true, this achievement is not shown in the UI until earned.")]
        public bool IsHidden { get; private set; }

        [Header("Rewards")]
        [field: SerializeField] public LootBoxDefinition RewardLootBox { get; private set; }
        [field: SerializeField] public BenefitDefinition RewardBenefit { get; private set; }
        [field: SerializeField] public ItemDefinition[] RewardItems { get; private set; }
        [field: SerializeField] public EffectDefinition[] RewardEffects { get; private set; }
        [field: SerializeField] public int GoldReward { get; private set; }
        [field: SerializeField] public int StatPointReward { get; private set; }
    }

    public enum AchievementTrigger
    {
        /// <summary>Earned when entity has a specific tag combination simultaneously.</summary>
        TagCombination,

        /// <summary>Global first: only the first crawler to achieve this tag combo gets it.</summary>
        FirstTagCombination,

        /// <summary>First mob kill.</summary>
        FirstKill,

        /// <summary>A crawler stat reaches a specific value.</summary>
        StatMilestone,

        /// <summary>Crawler reaches a specific floor.</summary>
        FloorReached,

        /// <summary>A skill reaches max level.</summary>
        SkillMaxed,

        /// <summary>First PVP kill.</summary>
        FirstPvpKill,

        /// <summary>Custom trigger — checked by name via SystemAI.TriggerCustom().</summary>
        Custom
    }
}
